### PR TITLE
Lists

### PR DESCRIPTION
**Pull request by alainkaegi**
Changed the `arrays.md` page to `lists.md`.

- Changed mentions of "arrays" to "lists" where approriate
- Redrew the figures
- Changed the description associated with figure in both `references.md` and `lists.md`

Let me know what you think.

### CODE REVIEW

**Comment by PeterDrake** [comment]
This generally looks good. Some thoughts:

I avoid using `l` as a variable name, because it's easily confused with `1` or `I`. (Indeed, in the font used in this comment `l` is indistinguishable from `I`: l vs I.)

I would argue for first showing the variable referring to the array with the numbers directly inside it. Then point out that technically the array contains references to the objects inside it, with a link to our references page.

Under Indexing, you inconsistently use the variable name as `l` in one place and `la` in another. Again, I would use the simpler numbers-directly-inside-the-array figure here.

A diagram of a multidimensional array would be extremely helpful for understanding why `m[1]` refers to one row.

In the section on slices, an example would help. Perhaps it should precede the general formulae.

In answer #2, it wouldn't hurt to point out that Python also lets you refer to this element as `a[-1]`.

In answer #5, an example would help clarify how the brackets are nested.

On the page about references, we should have a question similar to #9 here, illustrating that this is a shallow copy.

In #10, `l[-3:]` also works.

**Comment by PeterDrake** [comment]
On the page about references, I would argue that the 5 in the second diagram should not have a box around it. A box would represent `[5]`, not `5`.

Here, not the page on lists, is the place to explain that a list refers to a sequence of reference, not a sequence of values (which matters mainly in the case of shallow copies). We might also explain how to make a deep copy.

**Comment by alainkaegi** [comment]
You've mentioned before that `l` as a variable name is not great. Sorry I keep forgetting to avoid this name.

The new version of this branch addresses, I believe, most of your concerns.

I tried a new drawing style to distinguish a scalar from a list.  Let me know if it's successful.

I have run out time to fix the following:

- Shallow vs. deep copies.
- The way I've drawn lists is still misleading when it relates to immutable types, perhaps we should add a page on that topic to clarify the differences when doing deep copies where some elements are references to immutable types.
- Should we mention the function `id`?  Perhaps as a question?

I would address the above concerns in a separate set of commits (perhaps even after the semester is over; unless we feel it's important).

Old commit #id of the `lists` branch: 3ac0744
New commit #id fo the `lists` branch: 924dbd6

**Comment by PeterDrake** [comment]
This seems reasonable. We can talk about the drawing convention at some point.

A question seems like the right place to talk about `id`. In general, I think the main text should contain the main idea, explained concisely; interesting digressions belong in the questions.

**Comment by alainkaegi** [comment]
Merged.

**Pull request closed without merging**
