### PR TITLE
Created page on array-based structures

### PR DESCRIPTION
**Pull request by PeterDrake**
I haven't linked this to the front page yet because there's a pending pull request (on PeterDrake-patch-1) there. I'd be very interested in your feedback on this page, including code and diagram style.

BTW, PeterDrake-patch-2 was an error; feel free to kill that branch.

### CODE REVIEW

**Comment by alainkaegi** [comment]
I think this is very good.

I haven't looked at the actual code with great care yet.

I like the stack drawn vertically and its size referred to as height.

Generally I believe there is a few places where backticks are missing (to refer to items in the code).  For example: ArrayQueue?  I suspect you haven't necessarily made sure to cross every t's and to do every i's.

Here are some specific comments:

In the introductory material:

- "array's size must be allocated” ==> array’s size must be defined when it is created (size is not allocated, but the array is)
- “such as linked list” ==> add a link to the material

Stacks:

- “the capacity of `_data` may be larger…” ==> the capacity of `_data` must be larger…”
- “It also indicates the index...” ==> “It also useful as the index...”
- “would throw an EmptyStackException” ==> add a link to the Exception page (now or when the actual entry is written)
- “keeping the amortized running time of `pop` constant” ==> keep amortized `push` constant, rather?

Coda:

"Search, insertion, and deletion would require linear time, so more sophisticated data structures such as hash tables are preferred" ==> Search, insertion, and deletion would require linear time. If better runtime behavior is required, data structures such as hash tables might be preferred.

**Comment by PeterDrake** [comment]
Thanks for the comments. I've made a new commit incorporating almost all of them.

A question for the style guide: should we always use backticks when referring to a class name in text?

I disagree that the capacity *must* be larger than the current height of the stack. They can be equal, right?

As for the nonexistent pages, should we create and link to them all now, or make another pass after we have more content in place?

**Comment by alainkaegi** [comment]
You are right, the stack's size and its capacity may be the same.

re: should we always use backticks when referring to a class name in text?
> I'm flexible here, leaning towards using backticks

re: nonexistent pages
> I don't have a strong feeling one way or the other.  What's your experience been with Drakepedia?  Dangling references are okay if they don't stay that way too long.  A likely scenario is that we may get distracted at some point and a reference may stay dangling for longer than we care for.

Questions:

* Simulating Primitive Arrays: Get length of an array

  The text says that this operation takes constant time.  Is that creation time amortized per element?  Or are we assuming creating the entire array of n elements takes constant time?  I want to make sure students have the right mental image.  We may want to make the statement more precise.

Comments:

* Stacks

  "to allow the stack to grow and shrink without resizing the array," --> "to allow the stack to grow and shrink without resizing the array on every access,"

* Queues

  Shouldn't `_expand` reset `_front` and `_back` to 0 and len(_data) - 1, respectively?

  "(requiring copying everything into a larger array)": That's true only if enqueuing a new element.  I'm wondering if we should consider removing the parenthetical phrase.

* Lists

  `remove_at`: Should we also mention here that this function is susceptible to loitering?  Or leave this to the realization of students?  Or add the following question: "Which functions in ArrayStack, ArrayQueue, and ArrayList are susceptible to memory loitering?"?

I think this page is otherwise ready to go.

**Comment by PeterDrake** [comment]
Okay, let's use backticks and put that in the style guide. (Incredibly picky side issue: when displaying output of a program, do we wrap it in backticks even if it's a number?)

Yes, clearly [None] * n takes linear time; I don't know what I was thinking. This should be cleared up. Perhaps we could note somewhere that, in C, you can allocate an array in constant time, but the contents are uninitialized, creating security risks.

Your wording about stack resizing is indeed more precise. I approve.

Queues: You're right again! I wrote a test to expose this bug and fixed it. Here's the new version of that method:

    def _expand(self):
        n = len(self._data)
        new_data = [None] * n * 2
        for i in range(n):
            new_data[i] = self._data[(self._front + i) % n]
        self._front = 0
        self._back = len(self._data - 1)
        self._data = new_data

Question 5 already mentions loitering. Maybe add a sentence at the end of the answer: "Removing an item from an ArrayQueue or ArrayList has the same issue."

**Comment by PeterDrake** [comment]
Gyah, I wrote a test, "fixed" the bug, and then failed to run the test! THIS version works:

    def _expand(self):
        n = len(self._data)
        new_data = [None] * n * 2
        for i in range(n - 1):
            new_data[i] = self._data[(self._front + i) % n]
        self._front = 0
        self._back = n - 1
        self._data = new_data

**Comment by alainkaegi** [comment]
I've updated the commit according to your fixes and suggestions.

Please look at the last commit and comment on its usefulness.

If you're happy with this PR, I will merge it.

I will add backticks to class name in a separate commit (that will also update the style guide).

I would also use backticks even if the output is a single number.

**Comment by PeterDrake** [comment]
This looks very good. I would suggest only two changes:

In the explanation of creating an array in constant time in C, I would add a comma: "... its content is not initialized, creating a security risk."

The section on resizing the data array already mentions that "The new array is not merely one slot larger but *twice* as large, keeping the amortized running time of `push` constant.", so I don't think we need to also mention it in the paragraph right after the ArrayStack implementation.

**Comment by alainkaegi** [comment]
Ok, now I think the commit is ready to go, but where should I link it on the main page (README.md) and what name should I give it?

Also I just now re-read the entries we have for Stacks (data_structures/stacks.md) and Queues (data_structures/queues.md). Both of these pages have a section "array-based implementation" and both rely on a class called "Array".

Do you have any ideas on how to reconcile these two facets of array-based implementations of collections?

**Comment by alainkaegi** [comment]
I also like option b) better.

Should I just push these commits as is, without linked them up to README.md for now?

Yes, it's feasible to meet regularly.

**Comment by PeterDrake** [comment]
Yes, let's do that merging and we can make the changes to README.md (and the stack/queue pages) later.

**Comment by alainkaegi** [comment]
Merged this pull request into main.

**Pull request closed without merging**
